# Generated by Django 5.1.1 on 2024-09-17 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_notes_options_homework"),
    ]

    operations = [
        migrations.DeleteModel(
            name="homework",
        ),
    ]
